# Spacedust 软件路径配置文件
# 由 setup_tools.sh 自动生成

# 软件可执行文件路径
SPACEDUST_BIN="/mnt/f/OneDrive/文档（科研）/脚本/Download/13-A.baumannii/5-Spacedust/download/spacedust/bin/spacedust"
PRODIGAL_BIN="/mnt/f/OneDrive/文档（科研）/脚本/Download/13-A.baumannii/5-Spacedust/download/prodigal"
FOLDSEEK_BIN="/mnt/f/OneDrive/文档（科研）/脚本/Download/13-A.baumannii/5-Spacedust/download/foldseek/bin/foldseek"

# 目录路径
DOWNLOAD_DIR="/mnt/f/OneDrive/文档（科研）/脚本/Download/13-A.baumannii/5-Spacedust/download"
DATABASE_DIR="/mnt/f/OneDrive/文档（科研）/脚本/Download/13-A.baumannii/5-Spacedust/database"
BASE_DIR="/mnt/f/OneDrive/文档（科研）/脚本/Download/13-A.baumannii/5-Spacedust"

# 数据库路径
KEGG_DATABASE_PATH="/mnt/f/OneDrive/文档（科研）/脚本/Download/13-A.baumannii/5-Spacedust/database/KEGG_70/keggclusterdb"

# 生成时间
GENERATED_TIME="2025-09-22 15:29:51"
